// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/document_chunk.dart';
import 'data/source_document.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7884252392149657579),
      name: 'DocumentChunk',
      lastPropertyId: const obx_int.IdUid(9, 5183210205534347653),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5104097448885663469),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2773312476106348329),
            name: 'sourceDocId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(1, 5835059612257942195)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7694814823370839003),
            name: 'domain',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 9156551934147924925)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1971099292570157167),
            name: 'chunkIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5605239769686773788),
            name: 'pageNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3013841087649767444),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5519886905195973569),
            name: 'sourceLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 538099781949405266),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(3, 485495152841239922),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 384,
              neighborsPerNode: 32,
              indexingSearchCount: 200,
              distanceType: 2,
            )),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5183210205534347653),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4634653794525831309),
      name: 'SourceDocument',
      lastPropertyId: const obx_int.IdUid(9, 3179322975761709506),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3191156530925827094),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3482049495699991203),
            name: 'fileName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9077475294089281425),
            name: 'filePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3408920648566139915),
            name: 'domain',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3058311342162630937),
            name: 'pageCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1965200997919712067),
            name: 'chunkCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6141519509675964891),
            name: 'uploadedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 9099827949734747491),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3179322975761709506),
            name: 'errorMessage',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 4634653794525831309),
      lastIndexId: const obx_int.IdUid(3, 485495152841239922),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
        model: _entities[0],
        toOneRelations: (DocumentChunk object) => [],
        toManyRelations: (DocumentChunk object) => {},
        getId: (DocumentChunk object) => object.id,
        setId: (DocumentChunk object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentChunk object, fb.Builder fbb) {
          final domainOffset = fbb.writeString(object.domain);
          final textOffset = fbb.writeString(object.text);
          final sourceLabelOffset = fbb.writeString(object.sourceLabel);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListFloat32(object.embedding!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.sourceDocId);
          fbb.addOffset(2, domainOffset);
          fbb.addInt64(3, object.chunkIndex);
          fbb.addInt64(4, object.pageNumber);
          fbb.addOffset(5, textOffset);
          fbb.addOffset(6, sourceLabelOffset);
          fbb.addOffset(7, embeddingOffset);
          fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final sourceDocIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final domainParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final chunkIndexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final pageNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final sourceLabelParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final embeddingParam =
              const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = DocumentChunk(
              id: idParam,
              sourceDocId: sourceDocIdParam,
              domain: domainParam,
              chunkIndex: chunkIndexParam,
              pageNumber: pageNumberParam,
              text: textParam,
              sourceLabel: sourceLabelParam,
              embedding: embeddingParam,
              createdAt: createdAtParam);

          return object;
        }),
    SourceDocument: obx_int.EntityDefinition<SourceDocument>(
        model: _entities[1],
        toOneRelations: (SourceDocument object) => [],
        toManyRelations: (SourceDocument object) => {},
        getId: (SourceDocument object) => object.id,
        setId: (SourceDocument object, int id) {
          object.id = id;
        },
        objectToFB: (SourceDocument object, fb.Builder fbb) {
          final fileNameOffset = fbb.writeString(object.fileName);
          final filePathOffset = fbb.writeString(object.filePath);
          final domainOffset = fbb.writeString(object.domain);
          final statusOffset = fbb.writeString(object.status);
          final errorMessageOffset = object.errorMessage == null
              ? null
              : fbb.writeString(object.errorMessage!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, fileNameOffset);
          fbb.addOffset(2, filePathOffset);
          fbb.addOffset(3, domainOffset);
          fbb.addInt64(4, object.pageCount);
          fbb.addInt64(5, object.chunkCount);
          fbb.addInt64(6, object.uploadedAt.millisecondsSinceEpoch);
          fbb.addOffset(7, statusOffset);
          fbb.addOffset(8, errorMessageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final fileNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final filePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final domainParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final pageCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final chunkCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final uploadedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final errorMessageParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final object = SourceDocument(
              id: idParam,
              fileName: fileNameParam,
              filePath: filePathParam,
              domain: domainParam,
              pageCount: pageCountParam,
              chunkCount: chunkCountParam,
              uploadedAt: uploadedAtParam,
              status: statusParam,
              errorMessage: errorMessageParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[0]);

  /// See [DocumentChunk.sourceDocId].
  static final sourceDocId =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[1]);

  /// See [DocumentChunk.domain].
  static final domain =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[2]);

  /// See [DocumentChunk.chunkIndex].
  static final chunkIndex =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[3]);

  /// See [DocumentChunk.pageNumber].
  static final pageNumber =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[4]);

  /// See [DocumentChunk.text].
  static final text =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[5]);

  /// See [DocumentChunk.sourceLabel].
  static final sourceLabel =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[6]);

  /// See [DocumentChunk.embedding].
  static final embedding =
      obx.QueryHnswProperty<DocumentChunk>(_entities[0].properties[7]);

  /// See [DocumentChunk.createdAt].
  static final createdAt =
      obx.QueryDateProperty<DocumentChunk>(_entities[0].properties[8]);
}

/// [SourceDocument] entity fields to define ObjectBox queries.
class SourceDocument_ {
  /// See [SourceDocument.id].
  static final id =
      obx.QueryIntegerProperty<SourceDocument>(_entities[1].properties[0]);

  /// See [SourceDocument.fileName].
  static final fileName =
      obx.QueryStringProperty<SourceDocument>(_entities[1].properties[1]);

  /// See [SourceDocument.filePath].
  static final filePath =
      obx.QueryStringProperty<SourceDocument>(_entities[1].properties[2]);

  /// See [SourceDocument.domain].
  static final domain =
      obx.QueryStringProperty<SourceDocument>(_entities[1].properties[3]);

  /// See [SourceDocument.pageCount].
  static final pageCount =
      obx.QueryIntegerProperty<SourceDocument>(_entities[1].properties[4]);

  /// See [SourceDocument.chunkCount].
  static final chunkCount =
      obx.QueryIntegerProperty<SourceDocument>(_entities[1].properties[5]);

  /// See [SourceDocument.uploadedAt].
  static final uploadedAt =
      obx.QueryDateProperty<SourceDocument>(_entities[1].properties[6]);

  /// See [SourceDocument.status].
  static final status =
      obx.QueryStringProperty<SourceDocument>(_entities[1].properties[7]);

  /// See [SourceDocument.errorMessage].
  static final errorMessage =
      obx.QueryStringProperty<SourceDocument>(_entities[1].properties[8]);
}
