// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ai_chat_app/test/unit/chat_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_ai_chat_app/app/core/models/ai_provider.dart' as _i4;
import 'package:flutter_ai_chat_app/app/core/models/chat_message.dart' as _i6;
import 'package:flutter_ai_chat_app/app/core/services/api_provider_service.dart'
    as _i3;
import 'package:flutter_ai_chat_app/app/core/services/chat_history_service.dart'
    as _i8;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRx_0<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiProviderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiProviderService extends _i1.Mock
    implements _i3.ApiProviderService {
  MockApiProviderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Rx<_i4.AiProvider> get activeProvider =>
      (super.noSuchMethod(
            Invocation.getter(#activeProvider),
            returnValue: _FakeRx_0<_i4.AiProvider>(
              this,
              Invocation.getter(#activeProvider),
            ),
          )
          as _i2.Rx<_i4.AiProvider>);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void switchProvider(_i4.AiProvider? provider) => super.noSuchMethod(
    Invocation.method(#switchProvider, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> sendMessages(List<_i6.ChatMessage>? messages) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessages, [messages]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#sendMessages, [messages]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChatHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatHistoryService extends _i1.Mock
    implements _i8.ChatHistoryService {
  MockChatHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> saveMessage(String? chatId, _i6.ChatMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [chatId, message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.ChatMessage>> loadMessages(
    String? chatId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, [chatId], {#limit: limit}),
            returnValue: _i5.Future<List<_i6.ChatMessage>>.value(
              <_i6.ChatMessage>[],
            ),
          )
          as _i5.Future<List<_i6.ChatMessage>>);

  @override
  _i5.Future<void> updateMessage(String? chatId, _i6.ChatMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [chatId, message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [chatId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
